name: notebook_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - nglview
  - pip
  - pip:
    # biobox is compiled from its GitHub repository (default branch)
    - git+https://github.com/Degiacomi-Lab/biobox
